export const actionTypes = {
    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",

    LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",

    GET_PHOTOS_REQUEST: "GET_PHOTOS_REQUEST",
    GET_PHOTOS_SUCCESS: "GET_PHOTOS_SUCCESS",
    GET_PHOTOS_ERROR:"GET_PHOTOS_ERROR",

    SEARCH_PHOTO_REQUEST: "SEARCH_PHOTO_REQUEST",
    SEARCH_PHOTO_SUCCESS: "SEARCH_PHOTO_SUCCESS",
    SEARCH_PHOTO_ERROR: "SEARCH_PHOTO_ERROR",
    
    LIKE_PHOTO_REQUEST: "LIKE_PHOTO_REQUEST",
    LIKE_PHOTO_SUCCESS: "LIKE_PHOTO_SUCCESS",
    LIKE_PHOTO_ERROR: "LIKE_PHOTO_ERROR"
}